#!/usr/bin/env bash
# A bash script that displays a list of currently running processes
# Displays lines containing the bash word
# Requirements:
# You cannot use pgrep
# The third line of your script must be # shellcheck disable=SC2009

ps auxf | grep bash
yssmina
