#!/usr/bin/env bash
# A bash script that displays the content of the file /etc/passwd.
#   Only displays the username, user id, and the user home directory path.
#Requirements:
#    You must use the while loop (for and until are forbidden)

myfile="/etc/passwd"
while IFS= read -r line
do
     echo "$line" | cut -d":" -f1,3,6

done < "$myfile"
